### ISSUE TITLE
Right motor direction reversed on Leviathan

### ISSUE THREAD

**Issue by DrYerzinia** [CU-Robosub/cusub_common#5]
Right motor got replaced and now its foward/backward is reversed.  We need to change the PID_Pololu_matrix.py to flip its direction.  We also need to fix the corresponding issue in the sim at the same time.

**Comment by DrYerzinia** [comment]
Do we just want to leave this in the code and swap the wires on the ESC so we can have a neat all 1's flip_motor_array?

**Comment by barbierluke** [comment]
Yeah I think flipping hardware wise would be the cleanest. I'll budget some time for us fixing motors in the schedule this Saturday

**Comment by DrYerzinia** [comment]
Doing hardware fix instead
